"""
Django settings for new_kitchen project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# --------------------------------------------------
# BASE DIRECTORY
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'unsafe-secret-key')
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "sushiksha.pythonanywhere.com"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'products',
    "jazzmin",

    "users.apps.UsersConfig",
    'django_extensions',
    'enquiries.apps.EnquiriesConfig',
]

AUTH_USER_MODEL = 'users.User'



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'new_kitchen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # optional global templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'core.context_processors.cart_count',
                'core.context_processors.wishlist_count',  # <-- add this line

            ],
        },
    },
]




WSGI_APPLICATION = 'new_kitchen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# --------------------------------------------------
# STATIC FILES
# --------------------------------------------------
STATIC_URL = '/static/'

# Only include folders that actually exist
STATICFILES_DIRS = [
    BASE_DIR / 'core' / 'static',  # keep this if you have core/static
]

STATIC_ROOT = BASE_DIR / 'staticfiles'  # for collectstatic

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# --------------------------------------------------
# MEDIA FILES
# --------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --------------------------------------------------
# AUTHENTICATION REDIRECTS
# --------------------------------------------------
LOGIN_URL = "users:login"
LOGIN_REDIRECT_URL = '/products/'
LOGOUT_REDIRECT_URL = '/'


# --------------------------------------------------
# DEFAULT PRIMARY KEYDisallowedHost at /
# Request URL:	https://sushiksha.pythonanywhere.com/
# Django Version:	5.2.12
# Exception Type:	DisallowedHost
# Exception Value:	
# Invalid HTTP_HOST header: 'sushiksha.pythonanywhere.com'. You may need to add 'sushiksha.pythonanywhere.com' to ALLOWED_HOSTS.
# Exception Location:	/home/Sushiksha/kitchen-project/venv_jazzmin/lib/python3.10/site-packages/django/http/request.py, line 202, in get_host
# Raised during:	core.views.home
# Python Executable:	/usr/local/bin/uwsgi
# Python Version:	3.10.12
# Python Path:	
# ['/var/www',
#  '.',
#  '',
#  '/var/www',
#  '/usr/lib/python310.zip',
#  '/usr/lib/python3.10',
#  '/usr/lib/python3.10/lib-dynload',
#  '/home/Sushiksha/kitchen-project/venv_jazzmin/lib/python3.10/site-packages',
#  '/home/Sushiksha/kitchen-project']
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --------------------------------------------------
# RAZORPAY (PLACEHOLDERS)
# --------------------------------------------------
RAZORPAY_KEY_ID = 'your_key_id'
RAZORPAY_KEY_SECRET = 'your_secret'